# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.2.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QHeaderView, QLabel, QMainWindow,
    QMenu, QMenuBar, QPlainTextEdit, QProgressBar,
    QPushButton, QSizePolicy, QSlider, QStatusBar,
    QTableView, QTableWidget, QTableWidgetItem, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1378, 864)
        self.actionConnection = QAction(MainWindow)
        self.actionConnection.setObjectName(u"actionConnection")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.Z_down = QPushButton(self.centralwidget)
        self.Z_down.setObjectName(u"Z_down")
        self.Z_down.setGeometry(QRect(430, 240, 90, 150))
        self.Z_down.setMouseTracking(True)
        self.Z_down.setStyleSheet(u"image: url(:/images/assets/down_Z_arrow.png);\n"
"background-color: transparent;")
        self.Z_up = QPushButton(self.centralwidget)
        self.Z_up.setObjectName(u"Z_up")
        self.Z_up.setGeometry(QRect(430, 0, 90, 150))
        self.Z_up.setStyleSheet(u"image: url(:/images/assets/up_Z_arrow.png);\n"
"background-color: transparent;")
        self.X_up = QPushButton(self.centralwidget)
        self.X_up.setObjectName(u"X_up")
        self.X_up.setGeometry(QRect(160, 0, 90, 150))
        self.X_up.setStyleSheet(u"image: url(:/images/assets/up_X_arrow.png);\n"
"background-color: transparent;")
        self.X_down = QPushButton(self.centralwidget)
        self.X_down.setObjectName(u"X_down")
        self.X_down.setGeometry(QRect(160, 240, 90, 150))
        self.X_down.setStyleSheet(u"image: url(:/images/assets/down_X_arrow.png);\n"
"background-color: transparent;")
        self.Y_up = QPushButton(self.centralwidget)
        self.Y_up.setObjectName(u"Y_up")
        self.Y_up.setGeometry(QRect(10, 150, 150, 90))
        self.Y_up.setStyleSheet(u"image: url(:/images/assets/up_Y_arrow.png);\n"
"background-color: transparent;")
        self.Y_down = QPushButton(self.centralwidget)
        self.Y_down.setObjectName(u"Y_down")
        self.Y_down.setGeometry(QRect(250, 150, 150, 90))
        self.Y_down.setStyleSheet(u"image: url(:/images/assets/down_Y_arrow.png);\n"
"background-color: transparent;")
        self.home = QPushButton(self.centralwidget)
        self.home.setObjectName(u"home")
        self.home.setGeometry(QRect(160, 150, 90, 90))
        self.home.setStyleSheet(u"image: url(:/images/assets/home_button.png);\n"
"border-width: 2px;\n"
"")
        self.mesh = QPushButton(self.centralwidget)
        self.mesh.setObjectName(u"mesh")
        self.mesh.setGeometry(QRect(430, 150, 90, 90))
        self.mesh.setStyleSheet(u"image: url(:/images/assets/mesh_button.png);\n"
"background-color: transparent;\n"
"")
        self.play = QPushButton(self.centralwidget)
        self.play.setObjectName(u"play")
        self.play.setGeometry(QRect(30, 710, 90, 90))
        self.play.setStyleSheet(u"image: url(:/images/assets/play_button.png);\n"
"background-color: transparent;")
        self.pause = QPushButton(self.centralwidget)
        self.pause.setObjectName(u"pause")
        self.pause.setGeometry(QRect(180, 710, 90, 90))
        self.pause.setStyleSheet(u"image: url(:/images/assets/pause_button.png);\n"
"background-color: transparent;\n"
"border-color: rgb(0, 0, 0);")
        self.stop = QPushButton(self.centralwidget)
        self.stop.setObjectName(u"stop")
        self.stop.setGeometry(QRect(330, 710, 90, 90))
        self.stop.setMouseTracking(True)
        self.stop.setFocusPolicy(Qt.ClickFocus)
        self.stop.setStyleSheet(u"image: url(:/images/assets/stop_button.png);\n"
"background-color: transparent;\n"
"border-color: rgb(255, 0, 255);\n"
"border-width: 2px;\n"
"")
        self.IncX = QLabel(self.centralwidget)
        self.IncX.setObjectName(u"IncX")
        self.IncX.setGeometry(QRect(10, 450, 211, 31))
        font = QFont()
        font.setPointSize(24)
        self.IncX.setFont(font)
        self.Incy = QLabel(self.centralwidget)
        self.Incy.setObjectName(u"Incy")
        self.Incy.setGeometry(QRect(10, 500, 211, 31))
        self.Incy.setFont(font)
        self.IncZ = QLabel(self.centralwidget)
        self.IncZ.setObjectName(u"IncZ")
        self.IncZ.setGeometry(QRect(10, 550, 211, 31))
        self.IncZ.setFont(font)
        self.Mode_man = QPushButton(self.centralwidget)
        self.Mode_man.setObjectName(u"Mode_man")
        self.Mode_man.setGeometry(QRect(160, 620, 135, 76))
        self.Mode_man.setStyleSheet(u"image: url(:/images/assets/mode_manuel.png);\n"
"")
        self.Mode_auto = QPushButton(self.centralwidget)
        self.Mode_auto.setObjectName(u"Mode_auto")
        self.Mode_auto.setGeometry(QRect(10, 620, 135, 76))
        self.Mode_auto.setStyleSheet(u"image: url(:/images/assets/mode_auto.png);\n"
"")
        self.Mode_single = QPushButton(self.centralwidget)
        self.Mode_single.setObjectName(u"Mode_single")
        self.Mode_single.setGeometry(QRect(310, 620, 135, 76))
        self.Mode_single.setStyleSheet(u"image: url(:/images/assets/mode_cycle.png);\n"
"")
        self.progressBar = QProgressBar(self.centralwidget)
        self.progressBar.setObjectName(u"progressBar")
        self.progressBar.setGeometry(QRect(580, 710, 250, 45))
        self.progressBar.setValue(24)
        self.machine_Status = QLabel(self.centralwidget)
        self.machine_Status.setObjectName(u"machine_Status")
        self.machine_Status.setGeometry(QRect(590, 0, 291, 71))
        font1 = QFont()
        font1.setPointSize(30)
        font1.setBold(True)
        font1.setUnderline(True)
        self.machine_Status.setFont(font1)
        self.table_speeds = QTableView(self.centralwidget)
        self.table_speeds.setObjectName(u"table_speeds")
        self.table_speeds.setGeometry(QRect(590, 380, 256, 192))
        self.Speeds = QLabel(self.centralwidget)
        self.Speeds.setObjectName(u"Speeds")
        self.Speeds.setGeometry(QRect(590, 330, 111, 41))
        font2 = QFont()
        font2.setPointSize(24)
        font2.setBold(True)
        font2.setUnderline(True)
        self.Speeds.setFont(font2)
        self.openFile = QPushButton(self.centralwidget)
        self.openFile.setObjectName(u"openFile")
        self.openFile.setGeometry(QRect(580, 610, 150, 90))
        self.openFile.setStyleSheet(u"image: url(:/assets/ouvrir_fichier_boutton.png);")
        self.e_Stop = QPushButton(self.centralwidget)
        self.e_Stop.setObjectName(u"e_Stop")
        self.e_Stop.setGeometry(QRect(1170, 640, 181, 181))
        self.e_Stop.setStyleSheet(u"image: url(:/images/assets/e-stop.png);")
        self.gcodeView = QPlainTextEdit(self.centralwidget)
        self.gcodeView.setObjectName(u"gcodeView")
        self.gcodeView.setGeometry(QRect(1080, 0, 281, 511))
        self.IncXSld = QSlider(self.centralwidget)
        self.IncXSld.setObjectName(u"IncXSld")
        self.IncXSld.setGeometry(QRect(220, 455, 171, 31))
        self.IncXSld.setMaximum(10)
        self.IncXSld.setOrientation(Qt.Horizontal)
        self.IncXSld.setTickPosition(QSlider.TicksBelow)
        self.IncYSld = QSlider(self.centralwidget)
        self.IncYSld.setObjectName(u"IncYSld")
        self.IncYSld.setGeometry(QRect(220, 505, 171, 31))
        self.IncYSld.setMaximum(10)
        self.IncYSld.setOrientation(Qt.Horizontal)
        self.IncYSld.setTickPosition(QSlider.TicksBelow)
        self.IncZSld = QSlider(self.centralwidget)
        self.IncZSld.setObjectName(u"IncZSld")
        self.IncZSld.setGeometry(QRect(220, 555, 171, 31))
        self.IncZSld.setMaximum(10)
        self.IncZSld.setOrientation(Qt.Horizontal)
        self.IncZSld.setTickPosition(QSlider.TicksBelow)
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(220, 440, 16, 16))
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(380, 440, 16, 16))
        self.valueIncX = QLabel(self.centralwidget)
        self.valueIncX.setObjectName(u"valueIncX")
        self.valueIncX.setGeometry(QRect(420, 455, 51, 21))
        font3 = QFont()
        font3.setPointSize(14)
        self.valueIncX.setFont(font3)
        self.valueIncY = QLabel(self.centralwidget)
        self.valueIncY.setObjectName(u"valueIncY")
        self.valueIncY.setGeometry(QRect(420, 505, 51, 21))
        self.valueIncY.setFont(font3)
        self.valueIncZ = QLabel(self.centralwidget)
        self.valueIncZ.setObjectName(u"valueIncZ")
        self.valueIncZ.setGeometry(QRect(420, 555, 51, 21))
        self.valueIncZ.setFont(font3)
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(380, 490, 16, 16))
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(220, 490, 16, 16))
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(380, 540, 16, 16))
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(220, 540, 16, 16))
        self.tableStatus = QTableWidget(self.centralwidget)
        self.tableStatus.setObjectName(u"tableStatus")
        self.tableStatus.setGeometry(QRect(590, 60, 431, 192))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1378, 21))
        self.menuMenu = QMenu(self.menubar)
        self.menuMenu.setObjectName(u"menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuMenu.menuAction())
        self.menuMenu.addAction(self.actionConnection)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionConnection.setText(QCoreApplication.translate("MainWindow", u"Connection", None))
        self.Z_down.setText("")
        self.Z_up.setText("")
        self.X_up.setText("")
        self.X_down.setText("")
        self.Y_up.setText("")
        self.Y_down.setText("")
        self.home.setText("")
        self.mesh.setText("")
        self.play.setText("")
        self.pause.setText("")
        self.stop.setText("")
        self.IncX.setText(QCoreApplication.translate("MainWindow", u"Incr\u00e9ments X :", None))
        self.Incy.setText(QCoreApplication.translate("MainWindow", u"Incr\u00e9ments Y :", None))
        self.IncZ.setText(QCoreApplication.translate("MainWindow", u"Incr\u00e9ments Z :", None))
        self.Mode_man.setText("")
        self.Mode_auto.setText("")
        self.Mode_single.setText("")
        self.machine_Status.setText(QCoreApplication.translate("MainWindow", u"Machine Status", None))
        self.Speeds.setText(QCoreApplication.translate("MainWindow", u"Speeds", None))
        self.openFile.setText("")
        self.e_Stop.setText("")
        self.label.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"10", None))
        self.valueIncX.setText(QCoreApplication.translate("MainWindow", u"0 mm", None))
        self.valueIncY.setText(QCoreApplication.translate("MainWindow", u"0 mm", None))
        self.valueIncZ.setText(QCoreApplication.translate("MainWindow", u"0 mm", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"10", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"10", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.menuMenu.setTitle(QCoreApplication.translate("MainWindow", u"Menu", None))
    # retranslateUi

